// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Msg.Rtn.DepthMarketData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Evelynn.Base.Return {

  /// <summary>Holder for reflection information generated from Msg.Rtn.DepthMarketData.proto</summary>
  public static partial class MsgRtnDepthMarketDataReflection {

    #region Descriptor
    /// <summary>File descriptor for Msg.Rtn.DepthMarketData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgRtnDepthMarketDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1Nc2cuUnRuLkRlcHRoTWFya2V0RGF0YS5wcm90bxIHbXNnLnJ0bhoZUnRu",
            "LkRlcHRoTWFya2V0RGF0YS5wcm90byJBChVSdG5EZXB0aE1hcmtldERhdGFN",
            "c2cSKAoFRGVwdGgYASABKAsyGS5ydG4uRGVwdGhNYXJrZXREYXRhRmllbGRC",
            "SQoVaW8uZXZlbHlubi5iYXNlLnByb3RvQhpSdG5EZXB0aE1hcmtldERhdGFN",
            "c2dQcm90b6oCE0V2ZWx5bm4uQmFzZS5SZXR1cm5iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Evelynn.Base.Return.RtnDepthMarketDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Evelynn.Base.Return.RtnDepthMarketDataMsg), global::Evelynn.Base.Return.RtnDepthMarketDataMsg.Parser, new[]{ "Depth" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RtnDepthMarketDataMsg : pb::IMessage<RtnDepthMarketDataMsg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RtnDepthMarketDataMsg> _parser = new pb::MessageParser<RtnDepthMarketDataMsg>(() => new RtnDepthMarketDataMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RtnDepthMarketDataMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Evelynn.Base.Return.MsgRtnDepthMarketDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RtnDepthMarketDataMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RtnDepthMarketDataMsg(RtnDepthMarketDataMsg other) : this() {
      depth_ = other.depth_ != null ? other.depth_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RtnDepthMarketDataMsg Clone() {
      return new RtnDepthMarketDataMsg(this);
    }

    /// <summary>Field number for the "Depth" field.</summary>
    public const int DepthFieldNumber = 1;
    private global::Evelynn.Base.Return.DepthMarketDataField depth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Evelynn.Base.Return.DepthMarketDataField Depth {
      get { return depth_; }
      set {
        depth_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RtnDepthMarketDataMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RtnDepthMarketDataMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Depth, other.Depth)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (depth_ != null) hash ^= Depth.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (depth_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Depth);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (depth_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Depth);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (depth_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Depth);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RtnDepthMarketDataMsg other) {
      if (other == null) {
        return;
      }
      if (other.depth_ != null) {
        if (depth_ == null) {
          Depth = new global::Evelynn.Base.Return.DepthMarketDataField();
        }
        Depth.MergeFrom(other.Depth);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (depth_ == null) {
              Depth = new global::Evelynn.Base.Return.DepthMarketDataField();
            }
            input.ReadMessage(Depth);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (depth_ == null) {
              Depth = new global::Evelynn.Base.Return.DepthMarketDataField();
            }
            input.ReadMessage(Depth);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
